---
apiVersion: v1
kind: Service
metadata:
  name: hotel-book-cmd
  namespace: beta-app
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app.kubernetes.io/name: hotel-book-cmd