---
apiVersion: v1
kind: Service
metadata:
  name: hotel-book-query
  namespace: beta-app
spec:
  type: ClusterIP
  ports:
    - port: 9095
      targetPort: 9095
  selector:
    app.kubernetes.io/name: hotel-book-query