server:
  port: 5000
  servlet:
    context-path: "/hotel-book"

spring:
  data:
    mongodb:
      host: ${HOST_MONGO}
      port: 27017
      database: myStays
      username: admin
      password: password
  kafka:
    producer:
      bootstrap-servers: ${kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: HOTEL-BOOK-CMD

eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${HOST_REGISTRY:localhost}:8761/eureka/

auth:
  server:
    url: http://${HOST_AUTH:localhost}:9000
book:
  service:
    url: http://${HOST_BOOK_SERVICE:localhost}:9192

